version: 1.0.{build}-{branch}

image: Visual Studio 2017

clone_folder: C:\projects\Source

shallow_clone: true
clone_depth: 5

matrix:
  fast_finish: true

before_build:
- ps: nuget restore C:\projects\Source\CQL.sln

build:
  project: C:\projects\Source\CQL.sln
  parallel: true

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug
